name: atmos
description: Atmos — private couples messaging app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  dio: ^5.8.0+1
  web_socket_channel: ^3.0.2
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.7
  intl: ^0.20.2
  flutter_chess_board: ^1.0.1
  firebase_messaging: ^16.2.2
  firebase_core: ^4.9.0
  camera: ^0.12.0+1
  path_provider: ^2.1.5
  path: ^1.9.1
  just_audio: ^0.10.5
  youtube_explode_dart: ^3.1.0
  image_picker: ^1.2.2
  screen_protector: ^1.5.1
  local_auth: ^3.0.1
  record: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
